version: 0.2

env:
  variables:
    AWS_REGION: "us-east-1"
    # REPLACE WITH YOUR ACTUAL ACCOUNT ID
    ACCOUNT_ID: "341569028135" 
    ECR_REPO_NAME: "react-app-cicd"

phases:
  install:
    runtime-versions:
      nodejs: 20  # Changed from 24 to 20 (LTS) to ensure compatibility
    commands:
      - echo "Installing npm dependencies"
      - npm install

  pre_build:
    commands:
      - echo "Running lint checks"
      - npm run lint
      - echo "Running unit tests"
      - npm run test
      
      # Log in to Amazon ECR
      - echo "Logging in to Amazon ECR"
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
      
      # Define URL and Tag variables
      - REPO_URL=$ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO_NAME
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)

  build:
    commands:
      - echo "Building React application"
      - npm run build
      - echo "Building Docker image"
      - docker build -t $REPO_URL:$IMAGE_TAG .

  post_build:
    commands:
      - echo "Pushing Docker image to ECR"
      - docker push $REPO_URL:$IMAGE_TAG
      - echo "Build completed successfully"
      # Create imagedefinitions.json. The 'name' here must match the Container Name in ECS Task Definition (Step 6)
      - printf '[{"name":"react-app-cicd-1","imageUri":"%s"}]' $REPO_URL:$IMAGE_TAG > imagedefinitions.json

artifacts:
  files: imagedefinitions.json
