version: 0.2
env:
variables:
AWS_REGION: "us-east-1"
ACCOUNT_ID: "341569028135"
# Replace with your AWS account ID
ECR_REPO_NAME: "react-app-cicd"
DOCKER_USERNAME: "moelhamzawy1"
DOCKER_PASSWORD: "dckr_pat_Ml6flqoa8EMxpxyWIfbVjq1tYAg"
#production!
# If using Docker Hub
# Store in Secrets Manager in
phases:
install:
runtime-versions:
nodejs: 24
commands:
- echo "Installing npm dependencies"
- npm install
pre_build:
commands:
- echo "Running lint checks"
- npm run lint
- echo "Running unit tests"
- npm run test
# Authenticate with Docker Hub (if needed for base images)
- docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
# Authenticate with Amazon ECR
- echo "Logging in to Amazon ECR"
- aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
# Set image tag using commit SHA
- REPO_URL=$ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO_NAME
- IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
build:
commands:
- echo "Building React application"
- npm run build- echo "Building Docker image"
- docker build -t $REPO_URL:$IMAGE_TAG .
post_build:
commands:
- echo "Pushing Docker image to ECR"
- docker push $REPO_URL:$IMAGE_TAG
- echo "Build completed successfully"
# Create imagedefinitions.json for ECS deployment
- printf '[{"name":"react-app-cicd-1","imageUri":"%s"}]'
$REPO_URL:$IMAGE_TAG > imagedefinitions.json
artifacts:
files: imagedefinitions.json
cache:
paths:
- node_modules/**/*
- '/root/.npm/**/*'
